trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: echo "Pipeline to build, push and deploy application"
  displayName: 'Run a azure pipeline'
- task: Docker@2
  inputs:
    containerRegistry: 'saurabh'
    repository: 'saurabhDemoRegistry'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'


- task: Docker@2
  displayName: 'Run Docker Container'
  inputs:
    containerRegistry: 'saurabh'
    repository: 'saurabhDemoRegistry'
    command: 'run'
    runOptions: '-d -p 80:80 saurabh/saurabhDemoRegistry:latest'
