trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: A
    steps:
      - script: echo "Pipeline to build, push and deploy application"
        displayName: 'Run a azure pipeline'

      - task: Docker@2
        displayName: 'Build and Push Docker Image'
        inputs:
          containerRegistry: 'saurabh'
          repository: 'saurabhDemoRegistry'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'

  - job: B
    dependsOn: A  
    steps:
      - task: Docker@2
        displayName: 'Run Docker Container'
        inputs:
          containerRegistry: 'saurabh'
          repository: 'saurabhDemoRegistry'
          command: 'run'
          runOptions: '-d -p 80:80 saurabh/saurabhDemoRegistry:latest'
