trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: A
    steps:
      - script: echo "Pipeline to build, push and deploy application"
        displayName: 'Run an Azure pipeline'

      - task: Docker@2
        inputs:
          containerRegistry: 'saurabh'
          repository: 'saurabhDemoRegistry'
          command: 'buildAndPush'
          Dockerfile: './Dockerfile'
          buildContext: '.'
