trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: A
    steps:
      - script: echo "Pipeline to build, push and deploy application"
        displayName: 'Run an Azure pipeline'

      - task: Docker@2
        inputs:
          containerRegistry: 'saurabh'
          repository: 'saurabhDemoRegistry'
          command: 'buildAndPush'
          Dockerfile: './Dockerfile'
          buildContext: '.'
          tags: 'mynginx'

  - job: B
    dependsOn: A
    steps:
        - task: SSH@0
          inputs:
            sshEndpoint: 'azuredemopipelineconnection'
            runOptions: 'commands'
            commands: |
              az acr login --name saurabhdemoregistry
              docker pull saurabhdemoregistry.azurecr.io/mynginx
              docker run -d -p 80:80 --name mynginx-con saurabhdemoregistry.azurecr.io/mynginx
            readyTimeout: '20000'


      


