trigger:

- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: A
    steps:
      - script: echo "Pipeline to build, push and deploy application"
        displayName: 'Run a azure pipeline'

      - task: Docker@2
        displayName: 'Build and Push Docker Image'
        inputs:
          containerRegistry: 'saurabh'
          repository: 'saurabhDemoRegistry'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'

      - task: SSH@0
        inputs:
          sshEndpoint: 'azuredemopipelineconnection'
          runOptions: 'commands'
          commands: 'docker run --name mydocker -p 80:80 -d  '
          readyTimeout: '20000'
