trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: echo "Pipeline to build, push and deploy application"
  displayName: 'Run a azure pipeline'
- task: Docker@2
  inputs:
    containerRegistry: 'saurabh'
    repository: 'saurabhDemoRegistry'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'


- task: SSH@0
  inputs:
    sshEndpoint: 'azuredemopipelineconnection'
    runOptions: 'commands'
    commands: 'echo "hello world" > hello.txt'
    readyTimeout: '20000'


- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
